create table if not exists public.learning_content_drafts (
  page_key text primary key,
  content jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.learning_content_published (
  page_key text primary key,
  content jsonb not null default '{}'::jsonb,
  published_at timestamptz not null default now(),
  published_by uuid references auth.users(id) on delete set null
);

create table if not exists public.learning_content_revisions (
  id bigint generated by default as identity primary key,
  page_key text not null,
  content jsonb not null,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

create index if not exists learning_content_revisions_page_created_idx
  on public.learning_content_revisions (page_key, created_at desc);

create or replace function public.set_learning_content_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_learning_content_drafts_updated_at on public.learning_content_drafts;
create trigger set_learning_content_drafts_updated_at
before update on public.learning_content_drafts
for each row
execute function public.set_learning_content_updated_at();

alter table public.learning_content_drafts enable row level security;
alter table public.learning_content_published enable row level security;
alter table public.learning_content_revisions enable row level security;

grant select, insert, update, delete on public.learning_content_drafts to authenticated;
grant select on public.learning_content_published to anon, authenticated;
grant insert, update, delete on public.learning_content_published to authenticated;
grant select, insert, update, delete on public.learning_content_revisions to authenticated;
grant usage, select on sequence public.learning_content_revisions_id_seq to authenticated;

create policy "Public can read published learning content"
on public.learning_content_published
for select
to anon, authenticated
using (true);

create policy "Admins manage published learning content"
on public.learning_content_published
for all
to authenticated
using ((select private.has_role('admin'::text)))
with check ((select private.has_role('admin'::text)));

create policy "Admins manage learning content drafts"
on public.learning_content_drafts
for all
to authenticated
using ((select private.has_role('admin'::text)))
with check ((select private.has_role('admin'::text)));

create policy "Admins manage learning content revisions"
on public.learning_content_revisions
for all
to authenticated
using ((select private.has_role('admin'::text)))
with check ((select private.has_role('admin'::text)));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'learning-media',
  'learning-media',
  true,
  104857600,
  array['image/png','image/jpeg','image/webp','image/gif','video/mp4','video/webm']::text[]
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create policy "Public can read learning media"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'learning-media');

create policy "Admins can upload learning media"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'learning-media'
  and (select private.has_role('admin'::text))
);

create policy "Admins can update learning media"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'learning-media'
  and (select private.has_role('admin'::text))
)
with check (
  bucket_id = 'learning-media'
  and (select private.has_role('admin'::text))
);

create policy "Admins can delete learning media"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'learning-media'
  and (select private.has_role('admin'::text))
);;
